name: clean_architecture_cubit
description: A new Flutter project.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.0-64.0.dev <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5

  # API
  retrofit: ^4.0.1
  dio: ^5.3.0
  awesome_dio_interceptor: ^1.0.0
  # State Management
  flutter_bloc: ^8.1.3
  # Dependency Injection
  get_it: ^7.6.0
  # Database
  floor: ^1.4.2
  # Route Manager
  auto_route: ^7.7.1
  # Auth
  sign_in_with_apple: ^5.0.0
  flutter_facebook_auth: ^6.0.1
  google_sign_in: ^6.1.4
  # Others
  equatable: ^2.0.5
  oktoast: ^3.3.1
  flutter_secure_storage: ^8.0.0
  flutter_svg: ^2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  lint: ^2.1.2
  auto_route_generator: ^7.2.0
  retrofit_generator: ^7.0.8
  floor_generator: ^1.4.2
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6

flutter:
  uses-material-design: true
